Reorganizing Files and fixing class
jean-farinea/unitTestEn pull request #2
Opened 2023-08-03 11:59 UTC by jean-farinea

1.Organizing files with 1 task per brench
2.Fixing Class to return a boolean value instead of String.

2023-08-06 12:35 UTC, strzeleckik commented on src/test/java/lesson2/task5/IsEvenOrOddTest.java
> +    void verifyIfNumberIsEvenOrOdd() {
It's better to split it into two separate test functions like: shouldVerifyNumberAsEven, shouldVerifyNumberAsNotEven :)

2023-08-06 12:38 UTC, strzeleckik commented on src/test/java/lesson2/task5/IsEvenOrOddTest.java
> +    void verifyIfNumberIsEvenOrOdd() {
In next lessons we will learn new ways of writing tests that will allow us to write one method and test it against plenty of variations of data. But For now, when you are testing two different cases is better to split them

2023-08-06 12:39 UTC, strzeleckik requested changes
I left some comments with feedback

2023-08-06 12:40 UTC, strzeleckik commented on src/main/java/lesson2/task5/IsEvenOrOdd.java
> +        if (number %2 == 0) {
Take care of proper code formatting, ctrl + a and then ctrl + alt + l :)

2023-08-06 17:17 UTC, jean-farinea commented
Changes done, please review.

2023-08-10 18:55 UTC, strzeleckik approved these changes
Good job! :)

2023-08-11 11:51 UTC, merged