Lesson 6 Task 7 - Square Roor Exception
jean-farinea/unitTestEn pull request #23
Opened 2023-08-20 06:06 UTC by jean-farinea

1. SquareRoot class created with an exception for negative numbers.

2023-08-22 19:53 UTC, strzeleckik commented on src/main/java/lesson6/task7/SquareRoot.java
> +        try {
should be moved to unit tests

2023-08-22 19:53 UTC, strzeleckik requested changes
It would be good to add unit tests here

2023-08-25 06:27 UTC, jean-farinea commented
Adjusted. Please review.

2023-08-25 11:54 UTC, strzeleckik approved these changes
ok

2023-08-29 20:31 UTC, merged