Lesson 6 Task 8 - Personal Id Number
jean-farinea/unitTestEn pull request #24
Opened 2023-08-20 20:04 UTC by jean-farinea

1. ValidateIdNumber class created with method to check type and length of id.

2. Created two personal exception classes to match specific situations

2023-08-22 19:58 UTC, strzeleckik commented on src/main/java/lesson6/task8/ValidateIdNumber.java
> +public class ValidateIdNumber {
better name would be for example: IdValidator

2023-08-22 19:59 UTC, strzeleckik commented on src/main/java/lesson6/task8/ValidateIdNumber.java
> +public class ValidateIdNumber {
ValidateIdNumber fits more for method name

2023-08-22 19:59 UTC, strzeleckik commented on src/main/java/lesson6/task8/ValidateIdNumber.java
> +    public static void main(String[] args) {
move to unit tests

2023-08-22 19:59 UTC, strzeleckik requested changes
small changes required

2023-08-25 06:45 UTC, jean-farinea commented
Adjusted, please review.

2023-08-25 11:55 UTC, strzeleckik commented on src/main/java/lesson6/task8/idValidator.java
> +public class idValidator {
Class name starts with Capital always

2023-08-25 11:55 UTC, strzeleckik requested changes
small thing to change

2023-08-28 09:04 UTC, jean-farinea commented
Class and test class renamed. Please review.

2023-08-28 17:53 UTC, strzeleckik commented on src/test/java/lesson6/task8/IdValidatorTest.java
> +    void shouldValidatePersonalId() {
name of the method is shouldValidatePersonalId but you are expecting here also exception throw, it should be spiitted into separate tests

2023-08-29 10:24 UTC, jean-farinea commented
Test class adjusted. Please review.

2023-08-29 18:39 UTC, strzeleckik approved these changes
ok

2023-08-29 20:31 UTC, merged