Lesson 6 Task 9 - Divisibility by 3
jean-farinea/unitTestEn pull request #25
Opened 2023-08-20 20:41 UTC by jean-farinea

1. Class created to check if number is divisible by three within exception custom message

2023-08-22 20:01 UTC, strzeleckik commented on src/main/java/lesson6/task9/DivisibilityByThree.java
> +public class DivisibilityByThree {
different name: DisibilityChecker

2023-08-22 20:01 UTC, strzeleckik commented on src/main/java/lesson6/task9/DivisibilityByThree.java
> +    public static void main(String[] args) {
unit test

2023-08-22 20:01 UTC, strzeleckik requested changes
small changes

2023-08-28 09:56 UTC, jean-farinea commented
Changes done, please review.

2023-08-28 17:54 UTC, strzeleckik commented on src/test/java/lesson6/task9/DivisibilityCheckerTest.java
> +    void shouldCheckDivisibilityByThree() {
you are testing positive and negative scenario in one test, thats a bad practice

2023-08-29 10:34 UTC, jean-farinea commented
Test adjusted, please review.

2023-08-29 18:40 UTC, strzeleckik approved these changes
ok

2023-08-29 20:31 UTC, merged