Lesson 7 Task 2 - Capital letters
jean-farinea/unitTestEn pull request #27
Opened 2023-08-21 04:33 UTC by jean-farinea

1. Class ConvertToCapital created with a method to convert text to capital.

2. Test class created to verify if method is working as expected, including null and empty sources.

2023-08-22 20:04 UTC, strzeleckik commented on src/main/java/lesson7/task2/ConvertToCapital.java
> +public class ConvertToCapital {
for example TextConverter sounds better ;)

2023-08-22 20:05 UTC, strzeleckik commented on src/main/java/lesson7/task2/ConvertToCapital.java
> +        String convertedText = text.toUpperCase();
will it work with null? in my opinion it should throw NULL POINTER EXCEPTION

2023-08-22 20:06 UTC, strzeleckik requested changes
to check

2023-08-28 10:39 UTC, jean-farinea commented
Changes done, please review.

2023-08-28 17:56 UTC, strzeleckik commented on src/test/java/lesson7/task2/TextConverterTest.java
> +    void shouldCheckIfTextIsConvertedToCapital(String text) {
positive and negative scenario check in one test. should be splitted into separate methods or refactored

2023-08-29 10:40 UTC, jean-farinea commented
Test adjusted, please review.

2023-08-29 18:41 UTC, strzeleckik approved these changes
ok

2023-08-29 20:32 UTC, merged