Lesson 7 Task 4 - Text Length
jean-farinea/unitTestEn pull request #28
Opened 2023-08-21 05:06 UTC by jean-farinea

1. Class TextLength created with method to calculate the text lenght
2. Test class created within parameterizedtest and provided sample texts

2023-08-22 20:07 UTC, strzeleckik commented on src/main/java/lesson7/task4/TextLength.java
> +public class TextLength {
TextUtils maybe?

2023-08-22 20:07 UTC, strzeleckik commented on src/main/java/lesson7/task4/TextLength.java
> +        int textLength = text.length();
what if text is null? :)

2023-08-22 20:07 UTC, strzeleckik requested changes
feedback to consider

2023-08-28 11:19 UTC, jean-farinea commented
Changes done, please review.

2023-08-28 17:57 UTC, strzeleckik commented on src/test/java/lesson7/task4/TextUtilsTest.java
> +        Assertions.assertEquals(expectedLength, calculatedLength);
bad practice to check positive and negative scenario in one test

2023-08-28 17:57 UTC, strzeleckik requested changes
feedback in comment

2023-08-29 10:48 UTC, jean-farinea commented
Test adjusted, please review.

2023-08-29 18:42 UTC, strzeleckik approved these changes
ok

2023-08-29 20:32 UTC, merged