Conversion class minutes to seconds
jean-farinea/unitTestEn pull request #6
Opened 2023-08-10 08:48 UTC by jean-farinea

1. Conversion class created to convert minutes into seconds
2. Test class created for Conversion class

2023-08-10 18:42 UTC, strzeleckik commented on src/main/java/lesson3/task4/Conversion.java
> +public class Conversion {
In your potential system you can have many convertions: Currency convertion, Units convertions etc. You should name your classes in such a way that we will know exactly with what we are delaing with. Here in my opinion it should be sth like: TimeConverter

2023-08-10 18:42 UTC, strzeleckik requested changes
Small change

2023-08-20 04:19 UTC, jean-farinea commented
Class refactored and renamed within test class, please check.

2023-08-22 19:56 UTC, strzeleckik approved these changes
ok

2023-08-22 21:41 UTC, merged